---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ylx.
--- DateTime: 2024/7/17 11:28
--- Version: 0.0.1
---

---
--- This file is for dissection on exported PDU (inner TLS payload) from
--- origin Trojan traffic, since the exported PDU contains specific metadata,
--- using Decode As TLS will not recognize the header and payload properly.
---

---
--- PDU Protocol Format:
--- #######################################
--- #         PDU Metadata Header         #
--- #######################################
--- #             PDU Payload             # <-- Applying built-in TLS dissector API here.
--- #######################################
---

local trojan_pdu = Proto("TrojanPDU", "TrojanPDU Protocol")

local PROTOCOL_NAME = "TrojanPDU"

local pf_passwd = ProtoField.bytes("trojan_pdu.passwd", "Trojan PDU Password")

local pf_request = ProtoField.bytes("trojan_pdu.request", "Trojan PDU Request")
local pf_cmd = ProtoField.uint8("trojan_pdu.cmd", "Trojan PDU Command")
local pf_atype = ProtoField.uint8("trojan_pdu.atype", "Trojan PDU Address Type")
local pf_dst_addr = ProtoField.string("trojan_pdu.dst_addr", "Trojan PDU Destination Address")
local pf_dst_port = ProtoField.uint16("trojan_pdu.dst_port", "Trojan PDU Destination Port")
local pf_payload = ProtoField.bytes("trojan_pdu.payload", "Trojan PDU Payload")

local pf_tunneled_data = ProtoField.bytes("trojan_pdu.tunneled_data")

local pf_exported_pdu = Field.new("exported_pdu.exported_pdu")
local pf_data = Field.new("data.data")

function trojan_pdu.dissector(tvb, pktinfo, root)



    if pf_exported_pdu() == nil then
        return 0
    end

    --print("Dissector Called")

    local exported_pdu = pf_exported_pdu().range
    Dissector.get("tls"):call(exported_pdu:tvb(), pktinfo, root)

    if pf_data() == nil then
        return 0
    end

    local data = pf_data().range
    print("TLS Segment Data")

    Dissector.get("http2"):call(data:tvb(), pktinfo, root)
end

register_postdissector(trojan_pdu)